Word = 'Python'

print(Word[0])
print(Word[5])
print(Word[-0])
print(Word[-1])
print(Word[-6])
print(Word[0:2])
print(Word[2:5])
print(Word[:2])
print(Word[2:])
print(Word[:2]+Word[2:])
print(Word[-2:])
print(Word[42])
print(Word[4:42])
print(Word[42:])
Word[0] = 'J'
print('J'+Word[1:])
print(Word[:2]+'Py')
print(range(10))
print(range(5, 10))
print(range(0, 13, 6))
print(range(-10, -100, -30))
print(Word[-4:-2])
print(len(Word))
print(Word.lower())
print(Word.upper())
print(Word.replace('P', 'J'))
